"""baseline schema

Revision ID: fb1a2f3d7958
Revises: 
Create Date: 2026-09-10 22:50:19.552984

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fb1a2f3d7958'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('gmt_create', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=128), nullable=False),
    sa.Column('client_secret_last4', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('redirect_uris', sa.Text(), nullable=False),
    sa.Column('grant_types', sa.Text(), nullable=False),
    sa.Column('response_types', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('token_endpoint_auth_method', sa.String(length=32), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('skip_consent', sa.Boolean(), nullable=False),
    sa.Column('access_token_ttl', sa.Integer(), nullable=True),
    sa.Column('refresh_token_ttl', sa.Integer(), nullable=True),
    sa.Column('gmt_create', sa.DateTime(), nullable=False),
    sa.Column('gmt_modify', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_clients_client_id'), ['client_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=64), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('unionid', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('department_1', sa.String(length=100), nullable=True),
    sa.Column('department_2', sa.String(length=100), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('gmt_create', sa.DateTime(), nullable=False),
    sa.Column('gmt_modify', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_unionid'), ['unionid'], unique=False)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_uid', sa.String(length=255), nullable=False),
    sa.Column('unionid', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('raw_profile', sa.Text(), nullable=True),
    sa.Column('gmt_create', sa.DateTime(), nullable=False),
    sa.Column('gmt_modify', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_uid', name='uq_oauth_provider_uid')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_unionid'), ['unionid'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=16), nullable=True),
    sa.Column('nonce', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('gmt_create', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_authorization_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_authorization_codes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_authorization_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_authorization_codes_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('gmt_create', sa.DateTime(), nullable=False),
    sa.Column('gmt_modify', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_consent_user_client')
    )
    with op.batch_alter_table('oauth_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_consents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_consents_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('gmt_create', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_client_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('oauth_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_consents_client_id'))

    op.drop_table('oauth_consents')
    with op.batch_alter_table('oauth_authorization_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_authorization_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_authorization_codes_code'))
        batch_op.drop_index(batch_op.f('ix_oauth_authorization_codes_client_id'))

    op.drop_table('oauth_authorization_codes')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_unionid'))

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_unionid'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_clients_client_id'))

    op.drop_table('oauth_clients')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_events_user_id'))

    op.drop_table('login_events')
    # ### end Alembic commands ###
