"""branding overrides

Revision ID: 6006f98ac39e
Revises: fb1a2f3d7958
Create Date: 2026-09-13 23:51:52.183763

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6006f98ac39e'
down_revision: str | None = 'fb1a2f3d7958'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gmt_create', sa.DateTime(), nullable=False),
    sa.Column('gmt_modify', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'locale', name='uq_branding_app_locale')
    )
    with op.batch_alter_table('branding_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branding_overrides_app_id'), ['app_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branding_overrides_app_id'))

    op.drop_table('branding_overrides')
    # ### end Alembic commands ###
